language: java
sudo: required
jdk:
  - oraclejdk8
cache:  
  directories:  
   - $HOME/.m2  

before_install:
    - git clone --depth 1 https://github.com/kit-sdq/BuildUtilities.git /tmp/BuildUtilities
install: true

script: mvn clean verify

after_success:
- . /tmp/BuildUtilities/travis-ci/deploy.sh ecore2txt releng/edu.kit.ipd.sdq.mdsd.ecore2txt.updatesite repository kit-sdq updatesite

notifications:
  slack:
    secure: ctcODB54jc20GZLyvx0sx9QaKk2/dajFt20EV55EmVEbtaS+kd/AgppkSc/B4NEyvD3iNhOxpbwfDNXj1/A1/XEzPJeUg2n7bgeW4wjLb2K69tchYfsZS9hWJg+MqgpuNzKsr81Ep7Uhx7mdlOHe34AysmxpRs6DTBYoasGh+CiXa3mLXkEO/mmQ3VD/OVDxu4js+o6XVIxyl3XcDyxY9a9tq+4t4JOiAbk51B0yCltzSDI4cq36+bAYkLsjovbhy9Md4Gn2u73+jQGfAqM2Ixchd6+kVRVRrjCAACDB2HSdx2ObYxhH/73R+xk+ImNvAZfRS/cYmrxaz9abj/xO2PogKE+zP7DUjYtU5k4phdal2yDizhWKJmpLDEt0eiIY5dq3ThwQmiyZUYPl7brzG60z41hr31Y9MKJFwskxGx3s58dU1J2Y8B47uVx5PW5ON5wKzWbpYuG7+1T7CQdi8UloLK+Rc4mH8ToD9rL/c4dFfdaZaX8PbHvR+9em62k1kS+6ZWWPP13DvcfpUw9gfnFZMJ9geZYReLOU9NioJ3/O6o962E6NqTzKjNFYmgutGWjEStAgWgqNF2eXeIISTPg2ziDbqQzTU0fE7txhsqbhGM2ttw7UN0d1AovDBhOAt2jmS06QmuEz8vfLncwacQyDJPxQbt00arkM5nG52LA=
