language: java
sudo: required
jdk:
  - openjdk11
cache:  
  directories:  
   - $HOME/.m2  

before_install:
    - git clone --depth 1 https://github.com/kit-sdq/BuildUtilities.git /tmp/BuildUtilities
install: true

script: mvn clean verify

after_success:
- . /tmp/BuildUtilities/travis-ci/deploy.sh ecore2txt releng/edu.kit.ipd.sdq.mdsd.ecore2txt.updatesite repository kit-sdq updatesite

notifications:
  slack:
    secure: ctcODB54jc20GZLyvx0sx9QaKk2/dajFt20EV55EmVEbtaS+kd/AgppkSc/B4NEyvD3iNhOxpbwfDNXj1/A1/XEzPJeUg2n7bgeW4wjLb2K69tchYfsZS9hWJg+MqgpuNzKsr81Ep7Uhx7mdlOHe34AysmxpRs6DTBYoasGh+CiXa3mLXkEO/mmQ3VD/OVDxu4js+o6XVIxyl3XcDyxY9a9tq+4t4JOiAbk51B0yCltzSDI4cq36+bAYkLsjovbhy9Md4Gn2u73+jQGfAqM2Ixchd6+kVRVRrjCAACDB2HSdx2ObYxhH/73R+xk+ImNvAZfRS/cYmrxaz9abj/xO2PogKE+zP7DUjYtU5k4phdal2yDizhWKJmpLDEt0eiIY5dq3ThwQmiyZUYPl7brzG60z41hr31Y9MKJFwskxGx3s58dU1J2Y8B47uVx5PW5ON5wKzWbpYuG7+1T7CQdi8UloLK+Rc4mH8ToD9rL/c4dFfdaZaX8PbHvR+9em62k1kS+6ZWWPP13DvcfpUw9gfnFZMJ9geZYReLOU9NioJ3/O6o962E6NqTzKjNFYmgutGWjEStAgWgqNF2eXeIISTPg2ziDbqQzTU0fE7txhsqbhGM2ttw7UN0d1AovDBhOAt2jmS06QmuEz8vfLncwacQyDJPxQbt00arkM5nG52LA=
  email:
    recipients:
      secure: KYL353Mg3h1aLaY4HhSiVOJ9f2Mx6B8g4kgl7xTAjOuq1JrICdgvRudMsXKDRGKxot8XDoeWdF7I+iuUVy2+ybIhA7MZlRQixSABgVWnJQyIqUowS54HfIx/0DBh3rSOxb3TLn+WVhiaZfJhCRDQVJ/f2l4jWNtajC4hDhwEDof8K50zPCWFgqFnmsCUe6a0MumEmZflPX8Qc0QmOmREWvevqSq/TbjK07q292yTg4XAYE41PUyjNohUPZzf7O3CNBDPbF1nQDBIgylY6ozev++2Z9qCvRmBbHrZTueAFhr1+Pgf/87CNdSLPgkhJWp+aXiP60vENf7tJLTxp1BlI+bIN89Mf/fL/DQUEEjRTt7XhUzLjfz8S9xlaDbzunyZMRqn68mwZS+tPG4tqQGcBiBAcCdtY4UcLJS8PGhta0LXUnTkF1I05KPNziqBtkPYJuw9L1xKqHCbWcd3BSmH0EycSeDJzLBRCOtyokM7SNFRE/NqqVNXGpW4AFp4oAugga3drdRTYi2zwoQ8hPH7P/s6PenfS53rxsQxY8KZUwqLaospKPormL6Som9po41NU/fj4DBgDp/KvGqrCuiGefjxHhdT0P/+uRWugkqQP314LQvy3DsPUFHKRWsoE1MTQdfr25e7w1EoqQ6XEBE9pMDBtoQZ7Ng2gzNa4PeoGE8=
    on_success: never
    on_failure: always
